name: workflow with output variables (decimal inputs)

on:
  workflow_dispatch:
    inputs:
      firstNumber:
        description: "Enter first number (e.g. 13)"
        required: true
        default: "0"
        type: string

      secondNumber:
        description: "Enter second number (e.g. 5)"
        required: true
        default: "5"
        type: string

jobs:
  Math_Operations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

       #Step 1: Add & Multiply
      - name: Add and multiply numbers
        id: sumAndMultiply
        run: |
          echo "sum=$(( ${{ inputs.firstNumber }} + ${{ inputs.secondNumber }} ))" >> $GITHUB_OUTPUT
          echo "multiply=$(( ${{ inputs.firstNumber }} * ${{ inputs.secondNumber }} ))" >> $GITHUB_OUTPUT

      - name: Display sum & multiplication
        run: |
          echo "Sum result: ${{ steps.sumAndMultiply.outputs.sum }}"
          echo "Multiplication result: ${{ steps.sumAndMultiply.outputs.multiply }}"

       #Step 2: Subtract & Divide
      - name: Subtract and divide numbers
        id: subtractAndDivide
        run: |
          echo "subtract=$(( ${{ inputs.firstNumber }} - ${{ inputs.secondNumber }} ))" >> $GITHUB_OUTPUT
          echo "divide=$(( ${{ inputs.firstNumber }} / ${{ inputs.secondNumber }} ))" >> $GITHUB_OUTPUT

      - name: Display subtraction & division
        run: |
          echo "Subtraction result: ${{ steps.subtractAndDivide.outputs.subtract }}"
          echo "Division result: ${{ steps.subtractAndDivide.outputs.divide }}"
