name: workflow with output variables

on: 
  workflow_dispatch:
    inputs:
        Myname:
            description: "Please enter your name"
            required: true 
            default: "github user"
            type: string
        Environment:
            description: "please enter the environment"
            required: true
            type: choice

            options:
                - INT
                - PROD
                - DEV
        firstNumber:
            description: "please enter first number"
            required: true
            default: 0
            type : number 
        secondNumber:
            description: "please enter second number"
            required: true
            default: 0
            type: number 


jobs:
  UI_Tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code 
        uses: actions/checkout@v4

      - name: print this job name
        run : echo "UI_Tests"

      - name: print the context
        run : echo "It will run all UI test cases"

      - name: print inputs variable
        run : echo "one of the input variable is ${{inputs.Myname}}"
        
      - name: add and multiply the numbers
        id: sumAndMulti
        run: |
            echo "sum=$(( ${{inputs.firstNumber}} + ${{inputs.secondNumber}} ))" >> $GITHUB_OUTPUT
            echo "multi=$(( ${{inputs.firstNumber}} * ${{inputs.secondNumber}} ))" >> $GITHUB_OUTPUT 
  
      - name: display results
        run: |
            echo "Sum result: ${{ steps.sumAndMulti.outputs.sum}}"
            echo "Multiplication result: ${{steps.sumAndMulti.outputs.multi}}"

  API_Test:
    runs-on: ubuntu-latest

    steps: 
      - name: checkout code 
        uses: actions/checkout@v4
        
      - name: print this job name
        run: echo "API_test"

      - name: print the context 
        run: echo "It will run all api test cases"

      - name: print inputs other variable
        run: echo "one of the input variable is ${{inputs.Environment}}"
      
      - name: minus number
        id: subtraction
        run: echo "minus=$(( ${{inputs.firstNumber}} - ${{inputs.secondNumber}} ))" >> $GITHUB_OUTPUT
        
      - name: minus number
        id: division
        run: echo "div=$(( ${{inputs.firstNumber}} % ${{inputs.secondNumber}} ))" >> $GITHUB_OUTPUT   
  
      - name: display results
        run: |
            echo "Minus result: ${{ steps.subtraction.outputs.minus}}"
            echo "Division result: ${{steps.division.outputs.div}}"

